// <auto-generated />
using System;
using EcoRide.Modules.Trip.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoRide.Modules.Trip.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20251120113644_AddReceiptAndTripRating")]
    partial class AddReceiptAndTripRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trip")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoRide.Modules.Trip.Domain.Aggregates.ActiveTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_latitude");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_longitude");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<string>("RatingComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rating_comment");

                    b.Property<int?>("RatingStars")
                        .HasColumnType("integer")
                        .HasColumnName("rating_stars");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_trips_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_trips_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_trips_vehicle_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_trips_user_status");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("idx_trips_vehicle_status");

                    b.ToTable("trips", "trip");
                });

            modelBuilder.Entity("EcoRide.Modules.Trip.Domain.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_reservations_expires_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_reservations_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reservations_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_reservations_vehicle_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_reservations_user_status");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("idx_reservations_vehicle_status");

                    b.ToTable("reservations", "trip");
                });

            modelBuilder.Entity("EcoRide.Modules.Trip.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_latitude");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_longitude");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_details");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receipt_number");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<decimal>("TimeCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("time_cost");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<DateTime>("TripEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_end_time");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("TripStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_code");

                    b.Property<decimal>("WalletBalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("wallet_balance_after");

                    b.Property<decimal>("WalletBalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("wallet_balance_before");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_receipts_receipt_number");

                    b.HasIndex("TripId")
                        .IsUnique()
                        .HasDatabaseName("idx_receipts_trip_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_receipts_user_id");

                    b.ToTable("receipts", "trip");
                });
#pragma warning restore 612, 618
        }
    }
}
