// <auto-generated />
using System;
using EcoRide.Modules.Trip.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoRide.Modules.Trip.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trip")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoRide.Modules.Trip.Domain.Aggregates.ActiveTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_latitude");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_longitude");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_trips_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_trips_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_trips_vehicle_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_trips_user_status");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("idx_trips_vehicle_status");

                    b.ToTable("trips", "trip");
                });

            modelBuilder.Entity("EcoRide.Modules.Trip.Domain.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_reservations_expires_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_reservations_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reservations_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_reservations_vehicle_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_reservations_user_status");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("idx_reservations_vehicle_status");

                    b.ToTable("reservations", "trip");
                });
#pragma warning restore 612, 618
        }
    }
}
